server {
    listen 80;
    server_name iris.goeloria.de;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name iris.goeloria.de;

    ssl_certificate     /etc/letsencrypt/live/iris.goeloria.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/iris.goeloria.de/privkey.pem;

    # Frontend
    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
    }

    # Backend API
    location /api/ {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
